CREATE TABLE PERSON (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255) not null,
	last_name varchar(255) not null
);

insert into PERSON (first_name, last_name) values ('Peter','Gregory');
insert into PERSON (first_name, last_name) values ('George','Ballard');
insert into PERSON (first_name, last_name) values ('Randolph','Stevens');
insert into PERSON (first_name, last_name) values ('William','Welch');
insert into PERSON (first_name, last_name) values ('Armando','Walker');
insert into PERSON (first_name, last_name) values ('Paul','Park');
insert into PERSON (first_name, last_name) values ('Stewart','Cunningham');
insert into PERSON (first_name, last_name) values ('Joyce','Manning');
insert into PERSON (first_name, last_name) values ('Kent','Ray');
insert into PERSON (first_name, last_name) values ('Jasmine','Higgins');